name: flutter_qr_scanner_mypro
description: A QR Code Scanner App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  go_router: ^6.2.0
  iconly: ^1.0.1
  introduction_screen: ^3.1.6
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter
# Run command to generate native splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/img/ic_splash_logo.png"
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
